/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HireRouteImport } from './routes/hire'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as EmployerPortalRouteImport } from './routes/employer-portal'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as CandidatePortalRouteImport } from './routes/candidate-portal'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryPagesSaudiRouteImport } from './routes/country-pages/Saudi'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerPortalRoute = EmployerPortalRouteImport.update({
  id: '/employer-portal',
  path: '/employer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePortalRoute = CandidatePortalRouteImport.update({
  id: '/candidate-portal',
  path: '/candidate-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryPagesSaudiRoute = CountryPagesSaudiRouteImport.update({
  id: '/country-pages/Saudi',
  path: '/country-pages/Saudi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/candidate-portal': typeof CandidatePortalRoute
  '/candidates': typeof CandidatesRoute
  '/countries': typeof CountriesRoute
  '/employer-portal': typeof EmployerPortalRoute
  '/employers': typeof EmployersRoute
  '/hire': typeof HireRoute
  '/jobs': typeof JobsRoute
  '/country-pages/Saudi': typeof CountryPagesSaudiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/candidate-portal': typeof CandidatePortalRoute
  '/candidates': typeof CandidatesRoute
  '/countries': typeof CountriesRoute
  '/employer-portal': typeof EmployerPortalRoute
  '/employers': typeof EmployersRoute
  '/hire': typeof HireRoute
  '/jobs': typeof JobsRoute
  '/country-pages/Saudi': typeof CountryPagesSaudiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/candidate-portal': typeof CandidatePortalRoute
  '/candidates': typeof CandidatesRoute
  '/countries': typeof CountriesRoute
  '/employer-portal': typeof EmployerPortalRoute
  '/employers': typeof EmployersRoute
  '/hire': typeof HireRoute
  '/jobs': typeof JobsRoute
  '/country-pages/Saudi': typeof CountryPagesSaudiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/candidate-portal'
    | '/candidates'
    | '/countries'
    | '/employer-portal'
    | '/employers'
    | '/hire'
    | '/jobs'
    | '/country-pages/Saudi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/candidate-portal'
    | '/candidates'
    | '/countries'
    | '/employer-portal'
    | '/employers'
    | '/hire'
    | '/jobs'
    | '/country-pages/Saudi'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/candidate-portal'
    | '/candidates'
    | '/countries'
    | '/employer-portal'
    | '/employers'
    | '/hire'
    | '/jobs'
    | '/country-pages/Saudi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CandidatePortalRoute: typeof CandidatePortalRoute
  CandidatesRoute: typeof CandidatesRoute
  CountriesRoute: typeof CountriesRoute
  EmployerPortalRoute: typeof EmployerPortalRoute
  EmployersRoute: typeof EmployersRoute
  HireRoute: typeof HireRoute
  JobsRoute: typeof JobsRoute
  CountryPagesSaudiRoute: typeof CountryPagesSaudiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-portal': {
      id: '/employer-portal'
      path: '/employer-portal'
      fullPath: '/employer-portal'
      preLoaderRoute: typeof EmployerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-portal': {
      id: '/candidate-portal'
      path: '/candidate-portal'
      fullPath: '/candidate-portal'
      preLoaderRoute: typeof CandidatePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country-pages/Saudi': {
      id: '/country-pages/Saudi'
      path: '/country-pages/Saudi'
      fullPath: '/country-pages/Saudi'
      preLoaderRoute: typeof CountryPagesSaudiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CandidatePortalRoute: CandidatePortalRoute,
  CandidatesRoute: CandidatesRoute,
  CountriesRoute: CountriesRoute,
  EmployerPortalRoute: EmployerPortalRoute,
  EmployersRoute: EmployersRoute,
  HireRoute: HireRoute,
  JobsRoute: JobsRoute,
  CountryPagesSaudiRoute: CountryPagesSaudiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
